# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_remove_runnable_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='push',
            name='branch',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='branch',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
